import type { PortfolioContent, SiteCopy } from "@/app/lib/types";

export const DEFAULT_SITE_COPY: SiteCopy = {
  headerBrand: "PRC",
  navHome: "Home",
  navAbout: "About",
  navRadar: "Work Map",
  navSkills: "Skills",
  navProjects: "Projects",
  navHire: "Hire",
  navContact: "Contact",
  headerHireCta: "Hire Me",
  footerBrand: "RAHUL CHAKRADHAR PEREPOGU",
  footerLead:
    "AI systems builder focused on premium digital products, clear storytelling, and measurable impact.",
  footerQuickLinksTitle: "Quick Links",
  footerServicesTitle: "Services",
  footerServices: ["AI-powered platforms", "Product storytelling", "Frontend systems", "Creative direction"],
  footerCopyright: "© {year} PEREPOGU RAHUL CHAKRADHAR. All rights reserved.",
  footerMadeWith: "Designed with clarity and restraint",
  heroBadge: "Premium Digital Portfolio",
  heroEditorialBadge: "Interactive brand system",
  heroCTA1: "Explore Work",
  heroCTA2: "Start a Conversation",
  heroCurrentFocusLabel: "Current Focus",
  heroCurrentFocusText: "AI systems, editorial storytelling, and high-trust digital presence",
  heroSpotlights: [
    { title: "AI + Product", copy: "Systems that combine intelligence, utility, and a polished user experience." },
    { title: "Storytelling", copy: "Concise narrative framing that helps work read like a product, not a scrapbook." },
    { title: "Proof of Work", copy: "Projects, certifications, and skills organized as a single premium system." },
  ],
  aboutBadge: "About",
  aboutHeading: "Built with intention",
  aboutShortTitle: "Who I am",
  aboutShortCopy: "I build premium digital systems that are readable, useful, and memorable.",
  aboutBody1:
    "I’m Rahul Chakradhar, an AI-focused builder who values sharp messaging, practical systems, and a clean product mindset.",
  aboutBody2:
    "My work sits at the intersection of AI, design, and execution. I prefer concise interfaces, strong hierarchy, and experiences that feel calm under pressure.",
  aboutTags: ["AI Systems", "Product Thinking", "Storytelling", "Automation", "Creative Direction", "Backend Logic"],
  aboutFooter: "Structured to stay editable in the admin panel while feeling like a finished brand system on the public site.",
  skillsHeading: "Skills",
  skillsSubtitle: "A focused toolkit organized by capability, not by noise.",
  skillsViewMore: "View More Skills",
  skillsEmpty: "No skills found.",
  projectsHeading: "Projects",
  projectsSubtitle: "Product-style case studies with clear impact, tags, and actions.",
  projectsViewMore: "View More Projects",
  projectsEmpty: "No projects found.",
  certificationsHeading: "Certifications",
  certificationsSubtitle: "Verified credentials with issuer context and relevance tags.",
  certificationsViewMore: "View More Certifications",
  certificationsEmpty: "No certifications found.",
  contactHeading: "Contact",
  contactSubtitle: "For collaborations, consulting, or product ideas that need sharp execution.",
  contactIntroTitle: "Let's build something useful",
  contactIntroBody:
    "Share the context, scope, and timeline. I typically respond within 1-2 business days and prefer concrete briefs over vague asks.",
  contactSocialPrompt: "Connect on social",
  contactFormTitle: "Send a brief",
  contactSuccess: "Message sent successfully! I'll get back to you soon.",
  contactError: "Failed to send message. Please try again.",
  radarBadge: "Interactive Work Map",
  radarHeading: "Interactive Work Map",
  radarSubtitle: "A functional view of skills, projects, and certifications with clear navigation and live context.",
  radarFeatureTitle: "Connected system",
  radarFeatureCopy: "Clickable nodes, hover emphasis, and a compact dashboard make the relationships easy to read at a glance.",
  radarCommandCopy: "Use this layer to move between capabilities, proof points, and credentials without losing the overall structure.",
  radarExploreSkills: "Skills",
  radarSeeProjects: "Projects",
  radarViewCredentials: "Certifications",
};

export function getSiteCopy(content?: PortfolioContent | null): SiteCopy {
  return {
    ...DEFAULT_SITE_COPY,
    ...(content?.siteCopy || {}),
    heroSpotlights: content?.siteCopy?.heroSpotlights?.length ? content.siteCopy.heroSpotlights : DEFAULT_SITE_COPY.heroSpotlights,
    aboutTags: content?.siteCopy?.aboutTags?.length ? content.siteCopy.aboutTags : DEFAULT_SITE_COPY.aboutTags,
    footerServices: content?.siteCopy?.footerServices?.length ? content.siteCopy.footerServices : DEFAULT_SITE_COPY.footerServices,
  };
}