import type { PortfolioContent, SiteCopy } from "@/app/lib/types";

export const DEFAULT_SITE_COPY: SiteCopy = {
  headerBrand: "PRC",
  navHome: "Home",
  navAbout: "About",
  navRadar: "Radar",
  navSkills: "Skills",
  navProjects: "Projects",
  navHire: "Hire",
  navContact: "Contact",
  headerHireCta: "Hire Me",
  footerBrand: "RAHUL CHAKRADHAR PEREPOGU",
  footerLead:
    "Full Stack Developer & Creative Designer passionate about crafting exceptional digital experiences that blend innovation with functionality.",
  footerQuickLinksTitle: "Quick Links",
  footerServicesTitle: "Services",
  footerServices: ["Web Development", "UI/UX Design", "Mobile Apps", "Consulting"],
  footerCopyright: "© {year} PEREPOGU RAHUL CHAKRADHAR. All rights reserved.",
  footerMadeWith: "Made with love and lots of coffee",
  heroBadge: "Building Digital Impact",
  heroEditorialBadge: "Editorial Portfolio 2026",
  heroCTA1: "Explore My Work",
  heroCTA2: "Let's Collaborate",
  heroCurrentFocusLabel: "Current Focus",
  heroCurrentFocusText: "AI, content systems, and high-trust digital presence",
  heroSpotlights: [
    { title: "AI + Strategy", copy: "Creative systems that blend technical execution with storytelling." },
    { title: "Content Direction", copy: "Editorial thinking, visual framing, and clear messaging." },
    { title: "Portfolio Impact", copy: "Projects, certifications, and proof of work in one place." },
  ],
  aboutBadge: "Personal Story",
  aboutHeading: "About Me",
  aboutShortTitle: "A short version",
  aboutShortCopy: "I build work that feels personal, readable, and technically solid.",
  aboutBody1:
    "I am a passionate AI enthusiast, tech learner, content creator, and director who builds innovative solutions for real-world impact.",
  aboutBody2:
    "My focus lies in AI, technology, and content creation. I excel in problem-solving and logical reasoning, and I'm comfortable working across various fields - from software to hardware, irrespective of the domain. I prefer partnerships and entrepreneurship over traditional salaried jobs, seeking opportunities where I can generate revenue while doing what I love.",
  aboutTags: ["AI Enthusiast", "Tech Learner", "Content Creator", "Director", "Problem Solver", "Innovator"],
  aboutFooter: "Built to mix technical capability with a distinct voice, so the portfolio reads like a story instead of a catalog.",
  skillsHeading: "Skills & Expertise",
  skillsSubtitle: "A comprehensive toolkit of technologies and methodologies I use to bring ideas to life",
  skillsViewMore: "View More Skills",
  skillsEmpty: "No skills found.",
  projectsHeading: "Featured Projects",
  projectsSubtitle: "A showcase of my recent work, blending creativity with cutting-edge technology",
  projectsViewMore: "View More Projects",
  projectsEmpty: "No projects found.",
  certificationsHeading: "Certifications",
  certificationsSubtitle: "Professional certifications and credentials validating my expertise",
  certificationsViewMore: "View More Certifications",
  certificationsEmpty: "No certifications found.",
  contactHeading: "Get In Touch",
  contactSubtitle: "Ready to bring your ideas to life? Let's create something amazing together",
  contactIntroTitle: "Let's Connect",
  contactIntroBody:
    "I'm always excited to discuss new opportunities, share ideas, or collaborate on innovative projects. Whether you have a question or just want to say hello, I'd love to hear from you.",
  contactSocialPrompt: "Follow me on social media",
  contactFormTitle: "Send a Message",
  contactSuccess: "Message sent successfully! I'll get back to you soon.",
  contactError: "Failed to send message. Please try again.",
  radarBadge: "Portfolio Radar",
  radarHeading: "A live map of what I build",
  radarSubtitle: "An animated surface showing skills, projects, and certifications as a connected system instead of isolated tiles.",
  radarFeatureTitle: "Feature signal",
  radarFeatureCopy: "Featured items are prioritized, but the full set still stays visible and discoverable through the section links.",
  radarCommandCopy: "This layer is meant to feel like a command panel: compact, animated, and immediately readable from a glance.",
  radarExploreSkills: "Explore Skills",
  radarSeeProjects: "See Projects",
  radarViewCredentials: "View Credentials",
};

export function getSiteCopy(content?: PortfolioContent | null): SiteCopy {
  return {
    ...DEFAULT_SITE_COPY,
    ...(content?.siteCopy || {}),
    heroSpotlights: content?.siteCopy?.heroSpotlights?.length ? content.siteCopy.heroSpotlights : DEFAULT_SITE_COPY.heroSpotlights,
    aboutTags: content?.siteCopy?.aboutTags?.length ? content.siteCopy.aboutTags : DEFAULT_SITE_COPY.aboutTags,
    footerServices: content?.siteCopy?.footerServices?.length ? content.siteCopy.footerServices : DEFAULT_SITE_COPY.footerServices,
  };
}