export interface SkillLogoPreset {
  name: string;
  url: string;
  category: string;
  keywords?: string[];
}

const logo = (name: string, slug: string, category: string, keywords: string[] = []): SkillLogoPreset => ({
  name,
  category,
  keywords,
  url: `https://cdn.simpleicons.org/${slug}`,
});

const CORE_LOGOS: SkillLogoPreset[] = [
  logo('React', 'react', 'Frontend'),
  logo('Next.js', 'nextdotjs', 'Frontend'),
  logo('Vue.js', 'vuedotjs', 'Frontend'),
  logo('Nuxt', 'nuxt', 'Frontend'),
  logo('Svelte', 'svelte', 'Frontend'),
  logo('Angular', 'angular', 'Frontend'),
  logo('Tailwind CSS', 'tailwindcss', 'Frontend'),
  logo('Bootstrap', 'bootstrap', 'Frontend'),
  logo('Material UI', 'mui', 'Frontend'),
  logo('Framer Motion', 'framer', 'Frontend'),
  logo('HTML5', 'html5', 'Frontend'),
  logo('CSS3', 'css', 'Frontend'),
  logo('Sass', 'sass', 'Frontend'),
  logo('JavaScript', 'javascript', 'Languages'),
  logo('TypeScript', 'typescript', 'Languages'),
  logo('Node.js', 'nodedotjs', 'Backend'),
  logo('Express', 'express', 'Backend'),
  logo('NestJS', 'nestjs', 'Backend'),
  logo('Django', 'django', 'Backend'),
  logo('Flask', 'flask', 'Backend'),
  logo('FastAPI', 'fastapi', 'Backend'),
  logo('Spring', 'spring', 'Backend'),
  logo('Laravel', 'laravel', 'Backend'),
  logo('Ruby on Rails', 'rubyonrails', 'Backend'),
  logo('GraphQL', 'graphql', 'Backend'),
  logo('Apollo GraphQL', 'apollographql', 'Backend'),
  logo('gRPC', 'grpc', 'Backend'),
  logo('MongoDB', 'mongodb', 'Database'),
  logo('PostgreSQL', 'postgresql', 'Database'),
  logo('MySQL', 'mysql', 'Database'),
  logo('SQLite', 'sqlite', 'Database'),
  logo('Redis', 'redis', 'Database'),
  logo('Supabase', 'supabase', 'Database'),
  logo('Firebase', 'firebase', 'Cloud'),
  logo('AWS', 'amazonwebservices', 'Cloud'),
  logo('Azure', 'microsoftazure', 'Cloud'),
  logo('Google Cloud', 'googlecloud', 'Cloud'),
  logo('Vercel', 'vercel', 'Cloud'),
  logo('Netlify', 'netlify', 'Cloud'),
  logo('Cloudflare', 'cloudflare', 'Cloud'),
  logo('DigitalOcean', 'digitalocean', 'Cloud'),
  logo('Docker', 'docker', 'DevOps'),
  logo('Kubernetes', 'kubernetes', 'DevOps'),
  logo('Terraform', 'terraform', 'DevOps'),
  logo('Ansible', 'ansible', 'DevOps'),
  logo('GitHub Actions', 'githubactions', 'DevOps'),
  logo('Jenkins', 'jenkins', 'DevOps'),
  logo('Prometheus', 'prometheus', 'DevOps'),
  logo('Grafana', 'grafana', 'DevOps'),
  logo('Git', 'git', 'Tools'),
  logo('GitHub', 'github', 'Tools'),
  logo('GitLab', 'gitlab', 'Tools'),
  logo('Bitbucket', 'bitbucket', 'Tools'),
  logo('VS Code', 'visualstudiocode', 'Tools'),
  logo('Visual Studio', 'visualstudio', 'Tools'),
  logo('IntelliJ IDEA', 'intellijidea', 'Tools'),
  logo('PyCharm', 'pycharm', 'Tools'),
  logo('WebStorm', 'webstorm', 'Tools'),
  logo('Postman', 'postman', 'Tools'),
  logo('Insomnia', 'insomnia', 'Tools'),
  logo('Figma', 'figma', 'Design'),
  logo('Canva', 'canva', 'Design'),
  logo('Adobe Photoshop', 'adobephotoshop', 'Design'),
  logo('Adobe Illustrator', 'adobeillustrator', 'Design'),
  logo('Adobe Premiere Pro', 'adobepremierepro', 'Design'),
  logo('Adobe After Effects', 'adobeaftereffects', 'Design'),
  logo('Blender', 'blender', 'Design'),
  logo('DaVinci Resolve', 'davinciresolve', 'Design'),
  logo('Python', 'python', 'Languages'),
  logo('Java', 'openjdk', 'Languages'),
  logo('C', 'c', 'Languages'),
  logo('C++', 'cplusplus', 'Languages'),
  logo('C#', 'csharp', 'Languages'),
  logo('Go', 'go', 'Languages'),
  logo('Rust', 'rust', 'Languages'),
  logo('Kotlin', 'kotlin', 'Languages'),
  logo('Swift', 'swift', 'Languages'),
  logo('Dart', 'dart', 'Languages'),
  logo('PHP', 'php', 'Languages'),
  logo('Ruby', 'ruby', 'Languages'),
  logo('R', 'r', 'Languages'),
  logo('MATLAB', 'mathworks', 'Languages'),
  logo('NumPy', 'numpy', 'Data'),
  logo('Pandas', 'pandas', 'Data'),
  logo('Jupyter', 'jupyter', 'Data'),
  logo('Apache Spark', 'apachespark', 'Data'),
  logo('TensorFlow', 'tensorflow', 'AI/ML'),
  logo('PyTorch', 'pytorch', 'AI/ML'),
  logo('scikit-learn', 'scikitlearn', 'AI/ML'),
  logo('OpenAI', 'openai', 'AI/ML'),
  logo('Hugging Face', 'huggingface', 'AI/ML'),
  logo('LangChain', 'langchain', 'AI/ML'),
  logo('Linux', 'linux', 'Platform'),
  logo('Ubuntu', 'ubuntu', 'Platform'),
  logo('Windows', 'windows', 'Platform'),
  logo('macOS', 'apple', 'Platform'),
  logo('Android', 'android', 'Mobile'),
  logo('iOS', 'ios', 'Mobile'),
  logo('React Native', 'react', 'Mobile'),
  logo('Flutter', 'flutter', 'Mobile'),
  logo('Expo', 'expo', 'Mobile'),
  logo('Electron', 'electron', 'Desktop'),
  logo('Tauri', 'tauri', 'Desktop'),
  logo('NPM', 'npm', 'Package Managers'),
  logo('Yarn', 'yarn', 'Package Managers'),
  logo('pnpm', 'pnpm', 'Package Managers'),
  logo('Vite', 'vite', 'Build Tools'),
  logo('Webpack', 'webpack', 'Build Tools'),
  logo('Babel', 'babel', 'Build Tools'),
  logo('ESLint', 'eslint', 'Build Tools'),
  logo('Prettier', 'prettier', 'Build Tools'),
  logo('Jest', 'jest', 'Testing'),
  logo('Cypress', 'cypress', 'Testing'),
  logo('Playwright', 'playwright', 'Testing'),
  logo('Storybook', 'storybook', 'Testing'),
  logo('Selenium', 'selenium', 'Testing'),
  logo('Content Writing', 'notion', 'Content'),
  logo('Copywriting', 'grammarly', 'Content'),
  logo('SEO', 'googlesearchconsole', 'Content'),
  logo('YouTube', 'youtube', 'Content'),
  logo('Instagram', 'instagram', 'Content'),
  logo('LinkedIn', 'linkedin', 'Content'),
  logo('X (Twitter)', 'x', 'Content'),
  logo('Facebook', 'facebook', 'Content'),
  logo('TikTok', 'tiktok', 'Content'),
  logo('Pinterest', 'pinterest', 'Content'),
  logo('Discord', 'discord', 'Content'),
  logo('Slack', 'slack', 'Content'),
  logo('Notion', 'notion', 'Productivity'),
  logo('Trello', 'trello', 'Productivity'),
  logo('Asana', 'asana', 'Productivity'),
  logo('Jira', 'jira', 'Productivity'),
  logo('ClickUp', 'clickup', 'Productivity'),
  logo('Miro', 'miro', 'Productivity'),
  logo('Google Analytics', 'googleanalytics', 'Analytics'),
  logo('Tableau', 'tableau', 'Analytics'),
  logo('Power BI', 'powerbi', 'Analytics'),
  logo('Shopify', 'shopify', 'Commerce'),
  logo('WooCommerce', 'woocommerce', 'Commerce'),
  logo('Stripe', 'stripe', 'Commerce'),
  logo('Razorpay', 'razorpay', 'Commerce'),
  logo('PayPal', 'paypal', 'Commerce'),
  logo('WordPress', 'wordpress', 'CMS'),
  logo('Ghost', 'ghost', 'CMS'),
  logo('Strapi', 'strapi', 'CMS'),
  logo('Sanity', 'sanity', 'CMS'),
];

const EXTENDED_LOGOS: SkillLogoPreset[] = [
  logo('Astro', 'astro', 'Frontend'),
  logo('SolidJS', 'solid', 'Frontend'),
  logo('Qwik', 'qwik', 'Frontend'),
  logo('Alpine.js', 'alpinedotjs', 'Frontend'),
  logo('Lit', 'lit', 'Frontend'),
  logo('jQuery', 'jquery', 'Frontend'),
  logo('Three.js', 'threedotjs', 'Frontend'),
  logo('D3.js', 'd3dotjs', 'Frontend'),
  logo('Redux', 'redux', 'Frontend'),
  logo('Zustand', 'zustand', 'Frontend'),
  logo('React Query', 'reactquery', 'Frontend'),
  logo('Styled Components', 'styledcomponents', 'Frontend'),
  logo('Emotion', 'emotion', 'Frontend'),
  logo('Chakra UI', 'chakraui', 'Frontend'),
  logo('Ant Design', 'antdesign', 'Frontend'),
  logo('Radix UI', 'radixui', 'Frontend'),
  logo('Shadcn UI', 'shadcnui', 'Frontend'),
  logo('SWR', 'swr', 'Frontend'),
  logo('Prisma', 'prisma', 'Backend'),
  logo('Drizzle', 'drizzle', 'Backend'),
  logo('Sequelize', 'sequelize', 'Backend'),
  logo('TypeORM', 'typeorm', 'Backend'),
  logo('Mongoose', 'mongoose', 'Backend'),
  logo('Koa', 'koa', 'Backend'),
  logo('Hapi', 'hapi', 'Backend'),
  logo('Bun', 'bun', 'Backend'),
  logo('Deno', 'deno', 'Backend'),
  logo('Socket.IO', 'socketdotio', 'Backend'),
  logo('tRPC', 'trpc', 'Backend'),
  logo('RabbitMQ', 'rabbitmq', 'Backend'),
  logo('Apache Kafka', 'apachekafka', 'Backend'),
  logo('NATS', 'natsdotio', 'Backend'),
  logo('BullMQ', 'redis', 'Backend'),
  logo('Celery', 'celery', 'Backend'),
  logo('Apache Airflow', 'apacheairflow', 'Data'),
  logo('dbt', 'dbt', 'Data'),
  logo('Snowflake', 'snowflake', 'Data'),
  logo('BigQuery', 'googlebigquery', 'Data'),
  logo('Databricks', 'databricks', 'Data'),
  logo('Looker', 'looker', 'Data'),
  logo('Metabase', 'metabase', 'Data'),
  logo('ClickHouse', 'clickhouse', 'Database'),
  logo('MariaDB', 'mariadb', 'Database'),
  logo('Couchbase', 'couchbase', 'Database'),
  logo('Cassandra', 'apachecassandra', 'Database'),
  logo('Neo4j', 'neo4j', 'Database'),
  logo('Elasticsearch', 'elasticsearch', 'Database'),
  logo('OpenSearch', 'opensearch', 'Database'),
  logo('Meilisearch', 'meilisearch', 'Database'),
  logo('PlanetScale', 'planetscale', 'Database'),
  logo('CockroachDB', 'cockroachlabs', 'Database'),
  logo('Timescale', 'timescale', 'Database'),
  logo('Vault', 'vault', 'DevOps'),
  logo('Consul', 'consul', 'DevOps'),
  logo('Nomad', 'nomad', 'DevOps'),
  logo('ArgoCD', 'argo', 'DevOps'),
  logo('Pulumi', 'pulumi', 'DevOps'),
  logo('Helm', 'helm', 'DevOps'),
  logo('CircleCI', 'circleci', 'DevOps'),
  logo('Travis CI', 'travisci', 'DevOps'),
  logo('GitHub Copilot', 'githubcopilot', 'AI/ML'),
  logo('Perplexity', 'perplexity', 'AI/ML'),
  logo('Anthropic', 'anthropic', 'AI/ML'),
  logo('Cohere', 'cohere', 'AI/ML'),
  logo('Mistral AI', 'mistralai', 'AI/ML'),
  logo('Weights & Biases', 'weightsandbiases', 'AI/ML'),
  logo('MLflow', 'mlflow', 'AI/ML'),
  logo('Keras', 'keras', 'AI/ML'),
  logo('ONNX', 'onnx', 'AI/ML'),
  logo('NVIDIA', 'nvidia', 'AI/ML'),
  logo('CUDA', 'nvidia', 'AI/ML'),
  logo('Unity', 'unity', 'Game'),
  logo('Unreal Engine', 'unrealengine', 'Game'),
  logo('Godot', 'godotengine', 'Game'),
  logo('Steam', 'steam', 'Game'),
  logo('Arduino', 'arduino', 'Hardware'),
  logo('Raspberry Pi', 'raspberrypi', 'Hardware'),
  logo('ESPHome', 'esphome', 'Hardware'),
  logo('PlatformIO', 'platformio', 'Hardware'),
  logo('Home Assistant', 'homeassistant', 'Hardware'),
  logo('IoT', 'internetofthings', 'Hardware'),
  logo('Linux Mint', 'linuxmint', 'Platform'),
  logo('Debian', 'debian', 'Platform'),
  logo('Fedora', 'fedora', 'Platform'),
  logo('CentOS', 'centos', 'Platform'),
  logo('Arch Linux', 'archlinux', 'Platform'),
  logo('Kali Linux', 'kalilinux', 'Platform'),
  logo('WSL', 'linux', 'Platform'),
  logo('Heroku', 'heroku', 'Cloud'),
  logo('Render', 'render', 'Cloud'),
  logo('Railway', 'railway', 'Cloud'),
  logo('Fly.io', 'flydotio', 'Cloud'),
  logo('Linode', 'linode', 'Cloud'),
  logo('OVHcloud', 'ovh', 'Cloud'),
  logo('Cloudinary', 'cloudinary', 'Cloud'),
  logo('Sentry', 'sentry', 'Monitoring'),
  logo('Datadog', 'datadog', 'Monitoring'),
  logo('New Relic', 'newrelic', 'Monitoring'),
  logo('Bugsnag', 'bugsnag', 'Monitoring'),
  logo('LogRocket', 'logrocket', 'Monitoring'),
  logo('PagerDuty', 'pagerduty', 'Monitoring'),
  logo('SonarQube', 'sonarqube', 'Testing'),
  logo('Vitest', 'vitest', 'Testing'),
  logo('Mocha', 'mocha', 'Testing'),
  logo('Chai', 'chai', 'Testing'),
  logo('Testing Library', 'testinglibrary', 'Testing'),
  logo('Cucumber', 'cucumber', 'Testing'),
  logo('Appium', 'appium', 'Testing'),
  logo('BrowserStack', 'browserstack', 'Testing'),
  logo('Codecov', 'codecov', 'Testing'),
  logo('Sonatype', 'sonatype', 'Testing'),
  logo('Gulp', 'gulp', 'Build Tools'),
  logo('Grunt', 'grunt', 'Build Tools'),
  logo('Rollup', 'rollupdotjs', 'Build Tools'),
  logo('Parcel', 'parcel', 'Build Tools'),
  logo('Turborepo', 'turborepo', 'Build Tools'),
  logo('Nx', 'nx', 'Build Tools'),
  logo('Lerna', 'lerna', 'Build Tools'),
  logo('Bun PM', 'bun', 'Package Managers'),
  logo('Composer', 'composer', 'Package Managers'),
  logo('Poetry', 'poetry', 'Package Managers'),
  logo('Pip', 'pypi', 'Package Managers'),
  logo('Conda', 'anaconda', 'Package Managers'),
  logo('Homebrew', 'homebrew', 'Package Managers'),
  logo('Chocolatey', 'chocolatey', 'Package Managers'),
  logo('pnpm Workspaces', 'pnpm', 'Package Managers'),
  logo('OpenCV', 'opencv', 'AI/ML'),
  logo('Scipy', 'scipy', 'AI/ML'),
  logo('Pydantic', 'pydantic', 'AI/ML'),
  logo('Prefect', 'prefect', 'AI/ML'),
  logo('Ray', 'ray', 'AI/ML'),
  logo('Gradio', 'gradio', 'AI/ML'),
  logo('Streamlit', 'streamlit', 'AI/ML'),
  logo('H2O.ai', 'h2o', 'AI/ML'),
  logo('Apache MXNet', 'apachemxnet', 'AI/ML'),
  logo('Dataiku', 'dataiku', 'AI/ML'),
  logo('Kaggle', 'kaggle', 'AI/ML'),
  logo('Weights & Biases Sweeps', 'weightsandbiases', 'AI/ML'),
  logo('Obsidian', 'obsidian', 'Productivity'),
  logo('Airtable', 'airtable', 'Productivity'),
  logo('Monday.com', 'mondaydotcom', 'Productivity'),
  logo('Confluence', 'confluence', 'Productivity'),
  logo('Linear', 'linear', 'Productivity'),
  logo('Todoist', 'todoist', 'Productivity'),
  logo('Evernote', 'evernote', 'Productivity'),
  logo('Google Workspace', 'googleworkspace', 'Productivity'),
  logo('Microsoft 365', 'microsoft365', 'Productivity'),
  logo('Teams', 'microsoftteams', 'Productivity'),
  logo('Zoom', 'zoom', 'Productivity'),
  logo('Loom', 'loom', 'Productivity'),
  logo('Calendly', 'calendly', 'Productivity'),
  logo('HubSpot', 'hubspot', 'Marketing'),
  logo('Mailchimp', 'mailchimp', 'Marketing'),
  logo('Brevo', 'brevo', 'Marketing'),
  logo('ConvertKit', 'convertkit', 'Marketing'),
  logo('Substack', 'substack', 'Marketing'),
  logo('Buffer', 'buffer', 'Marketing'),
  logo('Hootsuite', 'hootsuite', 'Marketing'),
  logo('Semrush', 'semrush', 'Marketing'),
  logo('Ahrefs', 'ahrefs', 'Marketing'),
  logo('Google Ads', 'googleads', 'Marketing'),
  logo('Meta Ads', 'meta', 'Marketing'),
  logo('Analytics', 'googleanalytics', 'Analytics'),
  logo('Amplitude', 'amplitude', 'Analytics'),
  logo('Mixpanel', 'mixpanel', 'Analytics'),
  logo('Heap', 'heap', 'Analytics'),
  logo('Hotjar', 'hotjar', 'Analytics'),
  logo('Plausible', 'plausibleanalytics', 'Analytics'),
  logo('Matomo', 'matomo', 'Analytics'),
  logo('Umami', 'umami', 'Analytics'),
  logo('Grafana Loki', 'grafana', 'Monitoring'),
  logo('Kibana', 'kibana', 'Monitoring'),
  logo('Jaeger', 'jaeger', 'Monitoring'),
  logo('OpenTelemetry', 'opentelemetry', 'Monitoring'),
  logo('Promtail', 'prometheus', 'Monitoring'),
  logo('Figma FigJam', 'figma', 'Design'),
  logo('Sketch', 'sketch', 'Design'),
  logo('InVision', 'invision', 'Design'),
  logo('Adobe XD', 'adobexd', 'Design'),
  logo('Adobe Lightroom', 'adobelightroom', 'Design'),
  logo('Adobe Audition', 'adobeaudition', 'Design'),
  logo('Adobe Animate', 'adobeanimate', 'Design'),
  logo('Adobe InDesign', 'adobeindesign', 'Design'),
  logo('CorelDRAW', 'coreldraw', 'Design'),
  logo('Cinema 4D', 'cinema4d', 'Design'),
  logo('Autodesk', 'autodesk', 'Design'),
  logo('SketchUp', 'sketchup', 'Design'),
  logo('OBS Studio', 'obsstudio', 'Content'),
  logo('DaVinci Fusion', 'davinciresolve', 'Content'),
  logo('CapCut', 'capcut', 'Content'),
  logo('Shotcut', 'shotcut', 'Content'),
  logo('Audacity', 'audacity', 'Content'),
  logo('Spotify', 'spotify', 'Content'),
  logo('Anchor', 'anchor', 'Content'),
  logo('Vimeo', 'vimeo', 'Content'),
  logo('Twitch', 'twitch', 'Content'),
  logo('Behance', 'behance', 'Content'),
  logo('Dribbble', 'dribbble', 'Content'),
  logo('Medium', 'medium', 'Content'),
  logo('Dev.to', 'devdotto', 'Content'),
  logo('Hashnode', 'hashnode', 'Content'),
  logo('Reddit', 'reddit', 'Content'),
  logo('Quora', 'quora', 'Content'),
  logo('WhatsApp', 'whatsapp', 'Content'),
  logo('Telegram', 'telegram', 'Content'),
  logo('Signal', 'signal', 'Content'),
  logo('Messenger', 'messenger', 'Content'),
  logo('Snapchat', 'snapchat', 'Content'),
  logo('Threads', 'threads', 'Content'),
  logo('Xing', 'xing', 'Content'),
  logo('Patreon', 'patreon', 'Content'),
  logo('Buy Me A Coffee', 'buymeacoffee', 'Content'),
  logo('Ko-fi', 'kofi', 'Content'),
  logo('Amazon', 'amazon', 'Commerce'),
  logo('eBay', 'ebay', 'Commerce'),
  logo('Etsy', 'etsy', 'Commerce'),
  logo('OpenCart', 'opencart', 'Commerce'),
  logo('Magento', 'magento', 'Commerce'),
  logo('BigCommerce', 'bigcommerce', 'Commerce'),
  logo('PrestaShop', 'prestashop', 'Commerce'),
  logo('Square', 'square', 'Commerce'),
  logo('Wise', 'wise', 'Commerce'),
  logo('Payoneer', 'payoneer', 'Commerce'),
  logo('Adyen', 'adyen', 'Commerce'),
  logo('Mercado Pago', 'mercadopago', 'Commerce'),
  logo('WordPress Gutenberg', 'wordpress', 'CMS'),
  logo('Webflow', 'webflow', 'CMS'),
  logo('Framer Sites', 'framer', 'CMS'),
  logo('Wix', 'wix', 'CMS'),
  logo('Squarespace', 'squarespace', 'CMS'),
  logo('Contentful', 'contentful', 'CMS'),
  logo('Hygraph', 'hygraph', 'CMS'),
  logo('Storyblok', 'storyblok', 'CMS'),
  logo('DatoCMS', 'datocms', 'CMS'),
  logo('Keystone', 'keystone', 'CMS'),
  logo('Directus', 'directus', 'CMS'),
  logo('Payload CMS', 'payloadcms', 'CMS'),
  logo('Shopware', 'shopware', 'Commerce'),
  logo('Salesforce', 'salesforce', 'Business'),
  logo('SAP', 'sap', 'Business'),
  logo('Oracle', 'oracle', 'Business'),
  logo('ServiceNow', 'servicenow', 'Business'),
  logo('Stripe Connect', 'stripe', 'Business'),
  logo('Intercom', 'intercom', 'Business'),
  logo('Zendesk', 'zendesk', 'Business'),
  logo('Freshworks', 'freshworks', 'Business'),
  logo('Zoho', 'zoho', 'Business'),
  logo('QuickBooks', 'quickbooks', 'Business'),
  logo('Xero', 'xero', 'Business'),
  logo('Notepad++', 'notepadplusplus', 'Tools'),
  logo('Sublime Text', 'sublimetext', 'Tools'),
  logo('Vim', 'vim', 'Tools'),
  logo('Neovim', 'neovim', 'Tools'),
  logo('Emacs', 'gnuemacs', 'Tools'),
  logo('JetBrains', 'jetbrains', 'Tools'),
  logo('Android Studio', 'androidstudio', 'Tools'),
  logo('Xcode', 'xcode', 'Tools'),
  logo('CLion', 'clion', 'Tools'),
  logo('Rider', 'rider', 'Tools'),
  logo('Webflow Designer', 'webflow', 'Tools'),
  logo('Docker Desktop', 'docker', 'Tools'),
  logo('K9s', 'kubernetes', 'Tools'),
  logo('DBeaver', 'dbeaver', 'Tools'),
  logo('TablePlus', 'tableplus', 'Tools'),
  logo('MongoDB Compass', 'mongodb', 'Tools'),
  logo('FileZilla', 'filezilla', 'Tools'),
  logo('Termius', 'termius', 'Tools'),
  logo('Hyper', 'hyper', 'Tools'),
  logo('iTerm2', 'iterm2', 'Tools'),
  logo('PowerShell', 'powershell', 'Tools'),
  logo('Bash', 'gnubash', 'Tools'),
  logo('Zsh', 'zsh', 'Tools'),
  logo('Tmux', 'tmux', 'Tools'),
  logo('Nginx', 'nginx', 'Backend'),
  logo('Apache HTTP Server', 'apache', 'Backend'),
  logo('Caddy', 'caddy', 'Backend'),
  logo('Traefik', 'traefikproxy', 'Backend'),
  logo('HAProxy', 'haproxy', 'Backend'),
  logo('Gunicorn', 'gunicorn', 'Backend'),
  logo('Uvicorn', 'fastapi', 'Backend'),
  logo('PM2', 'pm2', 'Backend'),
  logo('SvelteKit', 'svelte', 'Frontend'),
  logo('Remix', 'remix', 'Frontend'),
  logo('Gatsby', 'gatsby', 'Frontend'),
  logo('Astro Starlight', 'astro', 'Frontend'),
  logo('Ionic', 'ionic', 'Mobile'),
  logo('Cordova', 'apachecordova', 'Mobile'),
  logo('Xamarin', 'xamarin', 'Mobile'),
  logo('Expo Router', 'expo', 'Mobile'),
  logo('React Navigation', 'react', 'Mobile'),
  logo('CocoaPods', 'cocoapods', 'Mobile'),
  logo('Fastlane', 'fastlane', 'Mobile'),
  logo('Gradle', 'gradle', 'Build Tools'),
  logo('Maven', 'apachemaven', 'Build Tools'),
  logo('Bazel', 'bazel', 'Build Tools'),
  logo('CMake', 'cmake', 'Build Tools'),
  logo('Meson', 'meson', 'Build Tools'),
  logo('Ninja', 'ninja', 'Build Tools'),
  logo('GNU Make', 'gnu', 'Build Tools'),
  logo('RubyGems', 'rubygems', 'Package Managers'),
  logo('NuGet', 'nuget', 'Package Managers'),
  logo('Maven Central', 'apachemaven', 'Package Managers'),
  logo('Cargo', 'rust', 'Package Managers'),
  logo('Crates.io', 'rust', 'Package Managers'),
  logo('Go Modules', 'go', 'Package Managers'),
  logo('Apt', 'debian', 'Package Managers'),
  logo('Yum', 'redhat', 'Package Managers'),
  logo('Pacman', 'archlinux', 'Package Managers'),
  logo('OpenAPI', 'openapiinitiative', 'Backend'),
  logo('Swagger', 'swagger', 'Backend'),
  logo('Insomnia Designer', 'insomnia', 'Backend'),
  logo('PostgREST', 'postgrest', 'Backend'),
  logo('Hasura', 'hasura', 'Backend'),
  logo('Auth0', 'auth0', 'Security'),
  logo('Okta', 'okta', 'Security'),
  logo('Keycloak', 'keycloak', 'Security'),
  logo('Cloudflare Zero Trust', 'cloudflare', 'Security'),
  logo('Fortinet', 'fortinet', 'Security'),
  logo('CrowdStrike', 'crowdstrike', 'Security'),
  logo('OWASP', 'owasp', 'Security'),
  logo('Burp Suite', 'burpsuite', 'Security'),
  logo('Kali Tools', 'kalilinux', 'Security'),
  logo('Wireshark', 'wireshark', 'Security'),
  logo('Nmap', 'nmap', 'Security'),
  logo('Security Headers', 'shield', 'Security', ['csp', 'x-frame-options', 'hsts']),
];

const deduped = new Map<string, SkillLogoPreset>();

for (const item of [...CORE_LOGOS, ...EXTENDED_LOGOS]) {
  const key = item.name.trim().toLowerCase();
  if (!deduped.has(key)) {
    deduped.set(key, item);
  }
}

export const SKILL_LOGO_PRESETS: SkillLogoPreset[] = Array.from(deduped.values());

export const SKILL_LOGO_CATEGORIES = [
  'All',
  ...Array.from(new Set(SKILL_LOGO_PRESETS.map((preset) => preset.category))).sort((a, b) => a.localeCompare(b)),
];

export const SKILL_LOGO_LOOKUP = Object.fromEntries(
  SKILL_LOGO_PRESETS.map((item) => [item.name.toLowerCase(), item.url])
);

export function resolveSkillIconUrl(iconValue?: string) {
  if (!iconValue) return '';
  const value = iconValue.trim();
  if (!value) return '';
  if (value.startsWith('http://') || value.startsWith('https://')) return value;
  const mapped = SKILL_LOGO_LOOKUP[value.toLowerCase()];
  return mapped || '';
}
