export interface SkillLogoPreset {
  name: string;
  url: string;
  category: string;
}

export const SKILL_LOGO_PRESETS: SkillLogoPreset[] = [
  { name: 'React', url: 'https://cdn.simpleicons.org/react', category: 'Frontend' },
  { name: 'Next.js', url: 'https://cdn.simpleicons.org/nextdotjs', category: 'Frontend' },
  { name: 'Vue.js', url: 'https://cdn.simpleicons.org/vuedotjs', category: 'Frontend' },
  { name: 'Nuxt', url: 'https://cdn.simpleicons.org/nuxt', category: 'Frontend' },
  { name: 'Svelte', url: 'https://cdn.simpleicons.org/svelte', category: 'Frontend' },
  { name: 'Angular', url: 'https://cdn.simpleicons.org/angular', category: 'Frontend' },
  { name: 'Tailwind CSS', url: 'https://cdn.simpleicons.org/tailwindcss', category: 'Frontend' },
  { name: 'Bootstrap', url: 'https://cdn.simpleicons.org/bootstrap', category: 'Frontend' },
  { name: 'Material UI', url: 'https://cdn.simpleicons.org/mui', category: 'Frontend' },
  { name: 'Framer Motion', url: 'https://cdn.simpleicons.org/framer', category: 'Frontend' },
  { name: 'HTML5', url: 'https://cdn.simpleicons.org/html5', category: 'Frontend' },
  { name: 'CSS3', url: 'https://cdn.simpleicons.org/css', category: 'Frontend' },
  { name: 'Sass', url: 'https://cdn.simpleicons.org/sass', category: 'Frontend' },
  { name: 'JavaScript', url: 'https://cdn.simpleicons.org/javascript', category: 'Languages' },
  { name: 'TypeScript', url: 'https://cdn.simpleicons.org/typescript', category: 'Languages' },
  { name: 'Node.js', url: 'https://cdn.simpleicons.org/nodedotjs', category: 'Backend' },
  { name: 'Express', url: 'https://cdn.simpleicons.org/express', category: 'Backend' },
  { name: 'NestJS', url: 'https://cdn.simpleicons.org/nestjs', category: 'Backend' },
  { name: 'Django', url: 'https://cdn.simpleicons.org/django', category: 'Backend' },
  { name: 'Flask', url: 'https://cdn.simpleicons.org/flask', category: 'Backend' },
  { name: 'FastAPI', url: 'https://cdn.simpleicons.org/fastapi', category: 'Backend' },
  { name: 'Spring', url: 'https://cdn.simpleicons.org/spring', category: 'Backend' },
  { name: 'Laravel', url: 'https://cdn.simpleicons.org/laravel', category: 'Backend' },
  { name: 'Ruby on Rails', url: 'https://cdn.simpleicons.org/rubyonrails', category: 'Backend' },
  { name: 'GraphQL', url: 'https://cdn.simpleicons.org/graphql', category: 'Backend' },
  { name: 'Apollo GraphQL', url: 'https://cdn.simpleicons.org/apollographql', category: 'Backend' },
  { name: 'gRPC', url: 'https://cdn.simpleicons.org/grpc', category: 'Backend' },
  { name: 'MongoDB', url: 'https://cdn.simpleicons.org/mongodb', category: 'Database' },
  { name: 'PostgreSQL', url: 'https://cdn.simpleicons.org/postgresql', category: 'Database' },
  { name: 'MySQL', url: 'https://cdn.simpleicons.org/mysql', category: 'Database' },
  { name: 'SQLite', url: 'https://cdn.simpleicons.org/sqlite', category: 'Database' },
  { name: 'Redis', url: 'https://cdn.simpleicons.org/redis', category: 'Database' },
  { name: 'Supabase', url: 'https://cdn.simpleicons.org/supabase', category: 'Database' },
  { name: 'Firebase', url: 'https://cdn.simpleicons.org/firebase', category: 'Cloud' },
  { name: 'AWS', url: 'https://cdn.simpleicons.org/amazonwebservices', category: 'Cloud' },
  { name: 'Azure', url: 'https://cdn.simpleicons.org/microsoftazure', category: 'Cloud' },
  { name: 'Google Cloud', url: 'https://cdn.simpleicons.org/googlecloud', category: 'Cloud' },
  { name: 'Vercel', url: 'https://cdn.simpleicons.org/vercel', category: 'Cloud' },
  { name: 'Netlify', url: 'https://cdn.simpleicons.org/netlify', category: 'Cloud' },
  { name: 'Cloudflare', url: 'https://cdn.simpleicons.org/cloudflare', category: 'Cloud' },
  { name: 'DigitalOcean', url: 'https://cdn.simpleicons.org/digitalocean', category: 'Cloud' },
  { name: 'Docker', url: 'https://cdn.simpleicons.org/docker', category: 'DevOps' },
  { name: 'Kubernetes', url: 'https://cdn.simpleicons.org/kubernetes', category: 'DevOps' },
  { name: 'Terraform', url: 'https://cdn.simpleicons.org/terraform', category: 'DevOps' },
  { name: 'Ansible', url: 'https://cdn.simpleicons.org/ansible', category: 'DevOps' },
  { name: 'GitHub Actions', url: 'https://cdn.simpleicons.org/githubactions', category: 'DevOps' },
  { name: 'Jenkins', url: 'https://cdn.simpleicons.org/jenkins', category: 'DevOps' },
  { name: 'Prometheus', url: 'https://cdn.simpleicons.org/prometheus', category: 'DevOps' },
  { name: 'Grafana', url: 'https://cdn.simpleicons.org/grafana', category: 'DevOps' },
  { name: 'Git', url: 'https://cdn.simpleicons.org/git', category: 'Tools' },
  { name: 'GitHub', url: 'https://cdn.simpleicons.org/github', category: 'Tools' },
  { name: 'GitLab', url: 'https://cdn.simpleicons.org/gitlab', category: 'Tools' },
  { name: 'Bitbucket', url: 'https://cdn.simpleicons.org/bitbucket', category: 'Tools' },
  { name: 'VS Code', url: 'https://cdn.simpleicons.org/visualstudiocode', category: 'Tools' },
  { name: 'Visual Studio', url: 'https://cdn.simpleicons.org/visualstudio', category: 'Tools' },
  { name: 'IntelliJ IDEA', url: 'https://cdn.simpleicons.org/intellijidea', category: 'Tools' },
  { name: 'PyCharm', url: 'https://cdn.simpleicons.org/pycharm', category: 'Tools' },
  { name: 'WebStorm', url: 'https://cdn.simpleicons.org/webstorm', category: 'Tools' },
  { name: 'Postman', url: 'https://cdn.simpleicons.org/postman', category: 'Tools' },
  { name: 'Insomnia', url: 'https://cdn.simpleicons.org/insomnia', category: 'Tools' },
  { name: 'Figma', url: 'https://cdn.simpleicons.org/figma', category: 'Design' },
  { name: 'Canva', url: 'https://cdn.simpleicons.org/canva', category: 'Design' },
  { name: 'Adobe Photoshop', url: 'https://cdn.simpleicons.org/adobephotoshop', category: 'Design' },
  { name: 'Adobe Illustrator', url: 'https://cdn.simpleicons.org/adobeillustrator', category: 'Design' },
  { name: 'Adobe Premiere Pro', url: 'https://cdn.simpleicons.org/adobepremierepro', category: 'Design' },
  { name: 'Adobe After Effects', url: 'https://cdn.simpleicons.org/adobeaftereffects', category: 'Design' },
  { name: 'Blender', url: 'https://cdn.simpleicons.org/blender', category: 'Design' },
  { name: 'DaVinci Resolve', url: 'https://cdn.simpleicons.org/davinciresolve', category: 'Design' },
  { name: 'Python', url: 'https://cdn.simpleicons.org/python', category: 'Languages' },
  { name: 'Java', url: 'https://cdn.simpleicons.org/openjdk', category: 'Languages' },
  { name: 'C', url: 'https://cdn.simpleicons.org/c', category: 'Languages' },
  { name: 'C++', url: 'https://cdn.simpleicons.org/cplusplus', category: 'Languages' },
  { name: 'C#', url: 'https://cdn.simpleicons.org/csharp', category: 'Languages' },
  { name: 'Go', url: 'https://cdn.simpleicons.org/go', category: 'Languages' },
  { name: 'Rust', url: 'https://cdn.simpleicons.org/rust', category: 'Languages' },
  { name: 'Kotlin', url: 'https://cdn.simpleicons.org/kotlin', category: 'Languages' },
  { name: 'Swift', url: 'https://cdn.simpleicons.org/swift', category: 'Languages' },
  { name: 'Dart', url: 'https://cdn.simpleicons.org/dart', category: 'Languages' },
  { name: 'PHP', url: 'https://cdn.simpleicons.org/php', category: 'Languages' },
  { name: 'Ruby', url: 'https://cdn.simpleicons.org/ruby', category: 'Languages' },
  { name: 'R', url: 'https://cdn.simpleicons.org/r', category: 'Languages' },
  { name: 'MATLAB', url: 'https://cdn.simpleicons.org/mathworks', category: 'Languages' },
  { name: 'NumPy', url: 'https://cdn.simpleicons.org/numpy', category: 'Data' },
  { name: 'Pandas', url: 'https://cdn.simpleicons.org/pandas', category: 'Data' },
  { name: 'Jupyter', url: 'https://cdn.simpleicons.org/jupyter', category: 'Data' },
  { name: 'Apache Spark', url: 'https://cdn.simpleicons.org/apachespark', category: 'Data' },
  { name: 'TensorFlow', url: 'https://cdn.simpleicons.org/tensorflow', category: 'AI/ML' },
  { name: 'PyTorch', url: 'https://cdn.simpleicons.org/pytorch', category: 'AI/ML' },
  { name: 'scikit-learn', url: 'https://cdn.simpleicons.org/scikitlearn', category: 'AI/ML' },
  { name: 'OpenAI', url: 'https://cdn.simpleicons.org/openai', category: 'AI/ML' },
  { name: 'Hugging Face', url: 'https://cdn.simpleicons.org/huggingface', category: 'AI/ML' },
  { name: 'LangChain', url: 'https://cdn.simpleicons.org/langchain', category: 'AI/ML' },
  { name: 'Linux', url: 'https://cdn.simpleicons.org/linux', category: 'Platform' },
  { name: 'Ubuntu', url: 'https://cdn.simpleicons.org/ubuntu', category: 'Platform' },
  { name: 'Windows', url: 'https://cdn.simpleicons.org/windows', category: 'Platform' },
  { name: 'macOS', url: 'https://cdn.simpleicons.org/apple', category: 'Platform' },
  { name: 'Android', url: 'https://cdn.simpleicons.org/android', category: 'Mobile' },
  { name: 'iOS', url: 'https://cdn.simpleicons.org/ios', category: 'Mobile' },
  { name: 'React Native', url: 'https://cdn.simpleicons.org/react', category: 'Mobile' },
  { name: 'Flutter', url: 'https://cdn.simpleicons.org/flutter', category: 'Mobile' },
  { name: 'Expo', url: 'https://cdn.simpleicons.org/expo', category: 'Mobile' },
  { name: 'Electron', url: 'https://cdn.simpleicons.org/electron', category: 'Desktop' },
  { name: 'Tauri', url: 'https://cdn.simpleicons.org/tauri', category: 'Desktop' },
  { name: 'NPM', url: 'https://cdn.simpleicons.org/npm', category: 'Package Managers' },
  { name: 'Yarn', url: 'https://cdn.simpleicons.org/yarn', category: 'Package Managers' },
  { name: 'pnpm', url: 'https://cdn.simpleicons.org/pnpm', category: 'Package Managers' },
  { name: 'Vite', url: 'https://cdn.simpleicons.org/vite', category: 'Build Tools' },
  { name: 'Webpack', url: 'https://cdn.simpleicons.org/webpack', category: 'Build Tools' },
  { name: 'Babel', url: 'https://cdn.simpleicons.org/babel', category: 'Build Tools' },
  { name: 'ESLint', url: 'https://cdn.simpleicons.org/eslint', category: 'Build Tools' },
  { name: 'Prettier', url: 'https://cdn.simpleicons.org/prettier', category: 'Build Tools' },
  { name: 'Jest', url: 'https://cdn.simpleicons.org/jest', category: 'Testing' },
  { name: 'Cypress', url: 'https://cdn.simpleicons.org/cypress', category: 'Testing' },
  { name: 'Playwright', url: 'https://cdn.simpleicons.org/playwright', category: 'Testing' },
  { name: 'Storybook', url: 'https://cdn.simpleicons.org/storybook', category: 'Testing' },
  { name: 'Selenium', url: 'https://cdn.simpleicons.org/selenium', category: 'Testing' },
  { name: 'Content Writing', url: 'https://cdn.simpleicons.org/notion', category: 'Content' },
  { name: 'Copywriting', url: 'https://cdn.simpleicons.org/grammarly', category: 'Content' },
  { name: 'SEO', url: 'https://cdn.simpleicons.org/googlesearchconsole', category: 'Content' },
  { name: 'YouTube', url: 'https://cdn.simpleicons.org/youtube', category: 'Content' },
  { name: 'Instagram', url: 'https://cdn.simpleicons.org/instagram', category: 'Content' },
  { name: 'LinkedIn', url: 'https://cdn.simpleicons.org/linkedin', category: 'Content' },
  { name: 'X (Twitter)', url: 'https://cdn.simpleicons.org/x', category: 'Content' },
  { name: 'Facebook', url: 'https://cdn.simpleicons.org/facebook', category: 'Content' },
  { name: 'TikTok', url: 'https://cdn.simpleicons.org/tiktok', category: 'Content' },
  { name: 'Pinterest', url: 'https://cdn.simpleicons.org/pinterest', category: 'Content' },
  { name: 'Discord', url: 'https://cdn.simpleicons.org/discord', category: 'Content' },
  { name: 'Slack', url: 'https://cdn.simpleicons.org/slack', category: 'Content' },
  { name: 'Notion', url: 'https://cdn.simpleicons.org/notion', category: 'Productivity' },
  { name: 'Trello', url: 'https://cdn.simpleicons.org/trello', category: 'Productivity' },
  { name: 'Asana', url: 'https://cdn.simpleicons.org/asana', category: 'Productivity' },
  { name: 'Jira', url: 'https://cdn.simpleicons.org/jira', category: 'Productivity' },
  { name: 'ClickUp', url: 'https://cdn.simpleicons.org/clickup', category: 'Productivity' },
  { name: 'Miro', url: 'https://cdn.simpleicons.org/miro', category: 'Productivity' },
  { name: 'Google Analytics', url: 'https://cdn.simpleicons.org/googleanalytics', category: 'Analytics' },
  { name: 'Tableau', url: 'https://cdn.simpleicons.org/tableau', category: 'Analytics' },
  { name: 'Power BI', url: 'https://cdn.simpleicons.org/powerbi', category: 'Analytics' },
  { name: 'Shopify', url: 'https://cdn.simpleicons.org/shopify', category: 'Commerce' },
  { name: 'WooCommerce', url: 'https://cdn.simpleicons.org/woocommerce', category: 'Commerce' },
  { name: 'Stripe', url: 'https://cdn.simpleicons.org/stripe', category: 'Commerce' },
  { name: 'Razorpay', url: 'https://cdn.simpleicons.org/razorpay', category: 'Commerce' },
  { name: 'PayPal', url: 'https://cdn.simpleicons.org/paypal', category: 'Commerce' },
  { name: 'WordPress', url: 'https://cdn.simpleicons.org/wordpress', category: 'CMS' },
  { name: 'Ghost', url: 'https://cdn.simpleicons.org/ghost', category: 'CMS' },
  { name: 'Strapi', url: 'https://cdn.simpleicons.org/strapi', category: 'CMS' },
  { name: 'Sanity', url: 'https://cdn.simpleicons.org/sanity', category: 'CMS' },
];

export const SKILL_LOGO_LOOKUP = Object.fromEntries(
  SKILL_LOGO_PRESETS.map((item) => [item.name.toLowerCase(), item.url])
);

export function resolveSkillIconUrl(iconValue?: string) {
  if (!iconValue) return '';
  const value = iconValue.trim();
  if (!value) return '';
  if (value.startsWith('http://') || value.startsWith('https://')) return value;
  const mapped = SKILL_LOGO_LOOKUP[value.toLowerCase()];
  return mapped || '';
}
